apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    tier: frotend
    app: nginx
  
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: app-port
      resources:
        limits:
          cpu: "0.5"
          memory: "134Mi"
      livenessProbe:
        exec:
          command:
            - echo
            - hodi
        # httpGet:
        #   path: /healthz
        #   port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      # readinessProb:
      