apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-container
        image: hothaifaz11/users-api
        ports:
        - containerPort: 5001
