apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: hothaifaz11/frontend
        ports:
        - containerPort: 80
        env:
        - name: USERS_API_URL
          value: "http://users-svc.default:5001"
        - name: AUTH_API_URL
          value: "http://auth-svc.default:5002"
        - name: TODOS_API_URL
          value: "http://todos-svc.default:5003"
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort